// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: api/service2/service2.proto

package service2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service2_PowerOn_FullMethodName  = "/Service2/PowerOn"
	Service2_PowerOff_FullMethodName = "/Service2/PowerOff"
	Service2_Reboot_FullMethodName   = "/Service2/Reboot"
)

// Service2Client is the client API for Service2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Service2Client interface {
	PowerOn(ctx context.Context, in *PowerOnDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error)
	PowerOff(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error)
	Reboot(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error)
}

type service2Client struct {
	cc grpc.ClientConnInterface
}

func NewService2Client(cc grpc.ClientConnInterface) Service2Client {
	return &service2Client{cc}
}

func (c *service2Client) PowerOn(ctx context.Context, in *PowerOnDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerDeviceResponse)
	err := c.cc.Invoke(ctx, Service2_PowerOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service2Client) PowerOff(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerDeviceResponse)
	err := c.cc.Invoke(ctx, Service2_PowerOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service2Client) Reboot(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerDeviceResponse)
	err := c.cc.Invoke(ctx, Service2_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Service2Server is the server API for Service2 service.
// All implementations must embed UnimplementedService2Server
// for forward compatibility.
type Service2Server interface {
	PowerOn(context.Context, *PowerOnDeviceRequest) (*PowerDeviceResponse, error)
	PowerOff(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error)
	Reboot(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error)
	mustEmbedUnimplementedService2Server()
}

// UnimplementedService2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedService2Server struct{}

func (UnimplementedService2Server) PowerOn(context.Context, *PowerOnDeviceRequest) (*PowerDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOn not implemented")
}
func (UnimplementedService2Server) PowerOff(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOff not implemented")
}
func (UnimplementedService2Server) Reboot(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedService2Server) mustEmbedUnimplementedService2Server() {}
func (UnimplementedService2Server) testEmbeddedByValue()                  {}

// UnsafeService2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Service2Server will
// result in compilation errors.
type UnsafeService2Server interface {
	mustEmbedUnimplementedService2Server()
}

func RegisterService2Server(s grpc.ServiceRegistrar, srv Service2Server) {
	// If the following call pancis, it indicates UnimplementedService2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service2_ServiceDesc, srv)
}

func _Service2_PowerOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerOnDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Service2Server).PowerOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service2_PowerOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Service2Server).PowerOn(ctx, req.(*PowerOnDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service2_PowerOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Service2Server).PowerOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service2_PowerOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Service2Server).PowerOff(ctx, req.(*PowerDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service2_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Service2Server).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service2_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Service2Server).Reboot(ctx, req.(*PowerDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service2_ServiceDesc is the grpc.ServiceDesc for Service2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service2",
	HandlerType: (*Service2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PowerOn",
			Handler:    _Service2_PowerOn_Handler,
		},
		{
			MethodName: "PowerOff",
			Handler:    _Service2_PowerOff_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _Service2_Reboot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service2/service2.proto",
}
