// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/service2/service2.proto

package service2

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerOnDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddr       string                 `protobuf:"bytes,1,opt,name=mac_addr,json=macAddr,proto3" json:"mac_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerOnDeviceRequest) Reset() {
	*x = PowerOnDeviceRequest{}
	mi := &file_api_service2_service2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerOnDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerOnDeviceRequest) ProtoMessage() {}

func (x *PowerOnDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service2_service2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerOnDeviceRequest.ProtoReflect.Descriptor instead.
func (*PowerOnDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_service2_service2_proto_rawDescGZIP(), []int{0}
}

func (x *PowerOnDeviceRequest) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

type PowerDeviceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Host           string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PrivateKeyPath string                 `protobuf:"bytes,3,opt,name=privateKeyPath,proto3" json:"privateKeyPath,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PowerDeviceRequest) Reset() {
	*x = PowerDeviceRequest{}
	mi := &file_api_service2_service2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerDeviceRequest) ProtoMessage() {}

func (x *PowerDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service2_service2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerDeviceRequest.ProtoReflect.Descriptor instead.
func (*PowerDeviceRequest) Descriptor() ([]byte, []int) {
	return file_api_service2_service2_proto_rawDescGZIP(), []int{1}
}

func (x *PowerDeviceRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PowerDeviceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PowerDeviceRequest) GetPrivateKeyPath() string {
	if x != nil {
		return x.PrivateKeyPath
	}
	return ""
}

type PowerDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowerDeviceResponse) Reset() {
	*x = PowerDeviceResponse{}
	mi := &file_api_service2_service2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerDeviceResponse) ProtoMessage() {}

func (x *PowerDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service2_service2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerDeviceResponse.ProtoReflect.Descriptor instead.
func (*PowerDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_service2_service2_proto_rawDescGZIP(), []int{2}
}

func (x *PowerDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_service2_service2_proto protoreflect.FileDescriptor

const file_api_service2_service2_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/service2/service2.proto\x1a api/google/api/annotations.proto\"1\n" +
	"\x14PowerOnDeviceRequest\x12\x19\n" +
	"\bmac_addr\x18\x01 \x01(\tR\amacAddr\"l\n" +
	"\x12PowerDeviceRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12&\n" +
	"\x0eprivateKeyPath\x18\x03 \x01(\tR\x0eprivateKeyPath\"/\n" +
	"\x13PowerDeviceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x82\x02\n" +
	"\bService2\x12R\n" +
	"\aPowerOn\x12\x15.PowerOnDeviceRequest\x1a\x14.PowerDeviceResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/poweron\x12R\n" +
	"\bPowerOff\x12\x13.PowerDeviceRequest\x1a\x14.PowerDeviceResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/poweroff\x12N\n" +
	"\x06Reboot\x12\x13.PowerDeviceRequest\x1a\x14.PowerDeviceResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/rebootB\x0eZ\fapi/service2b\x06proto3"

var (
	file_api_service2_service2_proto_rawDescOnce sync.Once
	file_api_service2_service2_proto_rawDescData []byte
)

func file_api_service2_service2_proto_rawDescGZIP() []byte {
	file_api_service2_service2_proto_rawDescOnce.Do(func() {
		file_api_service2_service2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service2_service2_proto_rawDesc), len(file_api_service2_service2_proto_rawDesc)))
	})
	return file_api_service2_service2_proto_rawDescData
}

var file_api_service2_service2_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_service2_service2_proto_goTypes = []any{
	(*PowerOnDeviceRequest)(nil), // 0: PowerOnDeviceRequest
	(*PowerDeviceRequest)(nil),   // 1: PowerDeviceRequest
	(*PowerDeviceResponse)(nil),  // 2: PowerDeviceResponse
}
var file_api_service2_service2_proto_depIdxs = []int32{
	0, // 0: Service2.PowerOn:input_type -> PowerOnDeviceRequest
	1, // 1: Service2.PowerOff:input_type -> PowerDeviceRequest
	1, // 2: Service2.Reboot:input_type -> PowerDeviceRequest
	2, // 3: Service2.PowerOn:output_type -> PowerDeviceResponse
	2, // 4: Service2.PowerOff:output_type -> PowerDeviceResponse
	2, // 5: Service2.Reboot:output_type -> PowerDeviceResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_service2_service2_proto_init() }
func file_api_service2_service2_proto_init() {
	if File_api_service2_service2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service2_service2_proto_rawDesc), len(file_api_service2_service2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service2_service2_proto_goTypes,
		DependencyIndexes: file_api_service2_service2_proto_depIdxs,
		MessageInfos:      file_api_service2_service2_proto_msgTypes,
	}.Build()
	File_api_service2_service2_proto = out.File
	file_api_service2_service2_proto_goTypes = nil
	file_api_service2_service2_proto_depIdxs = nil
}
