// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: api/power_mgmt/power_mgmt.proto

package power_mgmt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Power_Mgmt_PowerOn_FullMethodName  = "/Power_Mgmt/PowerOn"
	Power_Mgmt_PowerOff_FullMethodName = "/Power_Mgmt/PowerOff"
	Power_Mgmt_Reboot_FullMethodName   = "/Power_Mgmt/Reboot"
)

// Power_MgmtClient is the client API for Power_Mgmt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Power_MgmtClient interface {
	PowerOn(ctx context.Context, in *PowerOnDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error)
	PowerOff(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error)
	Reboot(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error)
}

type power_MgmtClient struct {
	cc grpc.ClientConnInterface
}

func NewPower_MgmtClient(cc grpc.ClientConnInterface) Power_MgmtClient {
	return &power_MgmtClient{cc}
}

func (c *power_MgmtClient) PowerOn(ctx context.Context, in *PowerOnDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerDeviceResponse)
	err := c.cc.Invoke(ctx, Power_Mgmt_PowerOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *power_MgmtClient) PowerOff(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerDeviceResponse)
	err := c.cc.Invoke(ctx, Power_Mgmt_PowerOff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *power_MgmtClient) Reboot(ctx context.Context, in *PowerDeviceRequest, opts ...grpc.CallOption) (*PowerDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PowerDeviceResponse)
	err := c.cc.Invoke(ctx, Power_Mgmt_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Power_MgmtServer is the server API for Power_Mgmt service.
// All implementations must embed UnimplementedPower_MgmtServer
// for forward compatibility.
type Power_MgmtServer interface {
	PowerOn(context.Context, *PowerOnDeviceRequest) (*PowerDeviceResponse, error)
	PowerOff(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error)
	Reboot(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error)
	mustEmbedUnimplementedPower_MgmtServer()
}

// UnimplementedPower_MgmtServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPower_MgmtServer struct{}

func (UnimplementedPower_MgmtServer) PowerOn(context.Context, *PowerOnDeviceRequest) (*PowerDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOn not implemented")
}
func (UnimplementedPower_MgmtServer) PowerOff(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PowerOff not implemented")
}
func (UnimplementedPower_MgmtServer) Reboot(context.Context, *PowerDeviceRequest) (*PowerDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedPower_MgmtServer) mustEmbedUnimplementedPower_MgmtServer() {}
func (UnimplementedPower_MgmtServer) testEmbeddedByValue()                    {}

// UnsafePower_MgmtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Power_MgmtServer will
// result in compilation errors.
type UnsafePower_MgmtServer interface {
	mustEmbedUnimplementedPower_MgmtServer()
}

func RegisterPower_MgmtServer(s grpc.ServiceRegistrar, srv Power_MgmtServer) {
	// If the following call pancis, it indicates UnimplementedPower_MgmtServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Power_Mgmt_ServiceDesc, srv)
}

func _Power_Mgmt_PowerOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerOnDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Power_MgmtServer).PowerOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Power_Mgmt_PowerOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Power_MgmtServer).PowerOn(ctx, req.(*PowerOnDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Power_Mgmt_PowerOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Power_MgmtServer).PowerOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Power_Mgmt_PowerOff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Power_MgmtServer).PowerOff(ctx, req.(*PowerDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Power_Mgmt_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Power_MgmtServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Power_Mgmt_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Power_MgmtServer).Reboot(ctx, req.(*PowerDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Power_Mgmt_ServiceDesc is the grpc.ServiceDesc for Power_Mgmt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Power_Mgmt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Power_Mgmt",
	HandlerType: (*Power_MgmtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PowerOn",
			Handler:    _Power_Mgmt_PowerOn_Handler,
		},
		{
			MethodName: "PowerOff",
			Handler:    _Power_Mgmt_PowerOff_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _Power_Mgmt_Reboot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/power_mgmt/power_mgmt.proto",
}
