// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/service1/service1.proto

package service1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_System_logs LogType = 0
	LogType_Kernel_logs LogType = 1
	LogType_Auth_logs   LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "System_logs",
		1: "Kernel_logs",
		2: "Auth_logs",
	}
	LogType_value = map[string]int32{
		"System_logs": 0,
		"Kernel_logs": 1,
		"Auth_logs":   2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_service1_service1_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_api_service1_service1_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_api_service1_service1_proto_rawDescGZIP(), []int{0}
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_api_service1_service1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service1_service1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_service1_service1_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type MetricsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage         float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage      float32                `protobuf:"fixed32,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	NetworkBandwidth uint64                 `protobuf:"varint,3,opt,name=network_bandwidth,json=networkBandwidth,proto3" json:"network_bandwidth,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_service1_service1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service1_service1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_service1_service1_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsResponse) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *MetricsResponse) GetNetworkBandwidth() uint64 {
	if x != nil {
		return x.NetworkBandwidth
	}
	return 0
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogType       LogType                `protobuf:"varint,1,opt,name=log_type,json=logType,proto3,enum=LogType" json:"log_type,omitempty"`
	DeviceId      int32                  `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_api_service1_service1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_service1_service1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_api_service1_service1_proto_rawDescGZIP(), []int{2}
}

func (x *LogsRequest) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_System_logs
}

func (x *LogsRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogFile       []byte                 `protobuf:"bytes,1,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_api_service1_service1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_service1_service1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_api_service1_service1_proto_rawDescGZIP(), []int{3}
}

func (x *LogResponse) GetLogFile() []byte {
	if x != nil {
		return x.LogFile
	}
	return nil
}

var File_api_service1_service1_proto protoreflect.FileDescriptor

const file_api_service1_service1_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/service1/service1.proto\x1a api/google/api/annotations.proto\"-\n" +
	"\x0eMetricsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\"~\n" +
	"\x0fMetricsResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x02R\vmemoryUsage\x12+\n" +
	"\x11network_bandwidth\x18\x03 \x01(\x04R\x10networkBandwidth\"O\n" +
	"\vLogsRequest\x12#\n" +
	"\blog_type\x18\x01 \x01(\x0e2\b.LogTypeR\alogType\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x05R\bdeviceId\"(\n" +
	"\vLogResponse\x12\x19\n" +
	"\blog_file\x18\x01 \x01(\fR\alogFile*:\n" +
	"\aLogType\x12\x0f\n" +
	"\vSystem_logs\x10\x00\x12\x0f\n" +
	"\vKernel_logs\x10\x01\x12\r\n" +
	"\tAuth_logs\x10\x022\x93\x01\n" +
	"\bService1\x12H\n" +
	"\n" +
	"GetMetrics\x12\x0f.MetricsRequest\x1a\x10.MetricsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/metrics\x12=\n" +
	"\aGetLogs\x12\f.LogsRequest\x1a\f.LogResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/logs0\x01B\x0eZ\fapi/service1b\x06proto3"

var (
	file_api_service1_service1_proto_rawDescOnce sync.Once
	file_api_service1_service1_proto_rawDescData []byte
)

func file_api_service1_service1_proto_rawDescGZIP() []byte {
	file_api_service1_service1_proto_rawDescOnce.Do(func() {
		file_api_service1_service1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_service1_service1_proto_rawDesc), len(file_api_service1_service1_proto_rawDesc)))
	})
	return file_api_service1_service1_proto_rawDescData
}

var file_api_service1_service1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_service1_service1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_service1_service1_proto_goTypes = []any{
	(LogType)(0),            // 0: LogType
	(*MetricsRequest)(nil),  // 1: MetricsRequest
	(*MetricsResponse)(nil), // 2: MetricsResponse
	(*LogsRequest)(nil),     // 3: LogsRequest
	(*LogResponse)(nil),     // 4: LogResponse
}
var file_api_service1_service1_proto_depIdxs = []int32{
	0, // 0: LogsRequest.log_type:type_name -> LogType
	1, // 1: Service1.GetMetrics:input_type -> MetricsRequest
	3, // 2: Service1.GetLogs:input_type -> LogsRequest
	2, // 3: Service1.GetMetrics:output_type -> MetricsResponse
	4, // 4: Service1.GetLogs:output_type -> LogResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_service1_service1_proto_init() }
func file_api_service1_service1_proto_init() {
	if File_api_service1_service1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service1_service1_proto_rawDesc), len(file_api_service1_service1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service1_service1_proto_goTypes,
		DependencyIndexes: file_api_service1_service1_proto_depIdxs,
		EnumInfos:         file_api_service1_service1_proto_enumTypes,
		MessageInfos:      file_api_service1_service1_proto_msgTypes,
	}.Build()
	File_api_service1_service1_proto = out.File
	file_api_service1_service1_proto_goTypes = nil
	file_api_service1_service1_proto_depIdxs = nil
}
