// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: api/script_mgmt/script_mgmt.proto

/*
Package script_mgmt is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package script_mgmt

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_Script_Mgmt_ScheduleScript_0(ctx context.Context, marshaler runtime.Marshaler, client Script_MgmtClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq ScheduleRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := client.ScheduleScript(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_Script_Mgmt_ScheduleScript_0(ctx context.Context, marshaler runtime.Marshaler, server Script_MgmtServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq ScheduleRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.ScheduleScript(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterScript_MgmtHandlerServer registers the http handlers for service Script_Mgmt to "mux".
// UnaryRPC     :call Script_MgmtServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterScript_MgmtHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterScript_MgmtHandlerServer(ctx context.Context, mux *runtime.ServeMux, server Script_MgmtServer) error {
	mux.Handle(http.MethodPost, pattern_Script_Mgmt_ScheduleScript_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/.Script_Mgmt/ScheduleScript", runtime.WithHTTPPathPattern("/api/v1/schedule"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Script_Mgmt_ScheduleScript_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_Script_Mgmt_ScheduleScript_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterScript_MgmtHandlerFromEndpoint is same as RegisterScript_MgmtHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterScript_MgmtHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterScript_MgmtHandler(ctx, mux, conn)
}

// RegisterScript_MgmtHandler registers the http handlers for service Script_Mgmt to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterScript_MgmtHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterScript_MgmtHandlerClient(ctx, mux, NewScript_MgmtClient(conn))
}

// RegisterScript_MgmtHandlerClient registers the http handlers for service Script_Mgmt
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "Script_MgmtClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "Script_MgmtClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "Script_MgmtClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterScript_MgmtHandlerClient(ctx context.Context, mux *runtime.ServeMux, client Script_MgmtClient) error {
	mux.Handle(http.MethodPost, pattern_Script_Mgmt_ScheduleScript_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/.Script_Mgmt/ScheduleScript", runtime.WithHTTPPathPattern("/api/v1/schedule"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Script_Mgmt_ScheduleScript_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_Script_Mgmt_ScheduleScript_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_Script_Mgmt_ScheduleScript_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "v1", "schedule"}, ""))
)

var (
	forward_Script_Mgmt_ScheduleScript_0 = runtime.ForwardResponseMessage
)
