// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/proxy_service/proxy.proto

package proxy_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Addr           string                 `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Port           string                 `protobuf:"bytes,3,opt,name=Port,proto3" json:"Port,omitempty"`
	ConnectionType string                 `protobuf:"bytes,4,opt,name=Connection_type,json=ConnectionType,proto3" json:"Connection_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_api_proxy_service_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_service_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proxy_service_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MetadataRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *MetadataRequest) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_proxy_service_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_service_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_proxy_service_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ModuleName    string                 `protobuf:"bytes,2,opt,name=Module_name,json=ModuleName,proto3" json:"Module_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_proxy_service_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proxy_service_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_proxy_service_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Request) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

var File_api_proxy_service_proxy_proto protoreflect.FileDescriptor

const file_api_proxy_service_proxy_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proxy_service/proxy.proto\"v\n" +
	"\x0fMetadataRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Addr\x18\x02 \x01(\tR\x04Addr\x12\x12\n" +
	"\x04Port\x18\x03 \x01(\tR\x04Port\x12'\n" +
	"\x0fConnection_type\x18\x04 \x01(\tR\x0eConnectionType\"$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8b\x01\n" +
	"\aRequest\x12&\n" +
	"\x04Data\x18\x01 \x03(\v2\x12.Request.DataEntryR\x04Data\x12\x1f\n" +
	"\vModule_name\x18\x02 \x01(\tR\n" +
	"ModuleName\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012i\n" +
	"\fProxyService\x12)\n" +
	"\bMetadata\x12\x10.MetadataRequest\x1a\t.Response\"\x00\x12.\n" +
	"\x15RecieveServiceRequest\x12\b.Request\x1a\t.Response\"\x00B\x13Z\x11api/proxy_serviceb\x06proto3"

var (
	file_api_proxy_service_proxy_proto_rawDescOnce sync.Once
	file_api_proxy_service_proxy_proto_rawDescData []byte
)

func file_api_proxy_service_proxy_proto_rawDescGZIP() []byte {
	file_api_proxy_service_proxy_proto_rawDescOnce.Do(func() {
		file_api_proxy_service_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proxy_service_proxy_proto_rawDesc), len(file_api_proxy_service_proxy_proto_rawDesc)))
	})
	return file_api_proxy_service_proxy_proto_rawDescData
}

var file_api_proxy_service_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proxy_service_proxy_proto_goTypes = []any{
	(*MetadataRequest)(nil), // 0: MetadataRequest
	(*Response)(nil),        // 1: Response
	(*Request)(nil),         // 2: Request
	nil,                     // 3: Request.DataEntry
}
var file_api_proxy_service_proxy_proto_depIdxs = []int32{
	3, // 0: Request.Data:type_name -> Request.DataEntry
	0, // 1: ProxyService.Metadata:input_type -> MetadataRequest
	2, // 2: ProxyService.RecieveServiceRequest:input_type -> Request
	1, // 3: ProxyService.Metadata:output_type -> Response
	1, // 4: ProxyService.RecieveServiceRequest:output_type -> Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proxy_service_proxy_proto_init() }
func file_api_proxy_service_proxy_proto_init() {
	if File_api_proxy_service_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proxy_service_proxy_proto_rawDesc), len(file_api_proxy_service_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proxy_service_proxy_proto_goTypes,
		DependencyIndexes: file_api_proxy_service_proxy_proto_depIdxs,
		MessageInfos:      file_api_proxy_service_proxy_proto_msgTypes,
	}.Build()
	File_api_proxy_service_proxy_proto = out.File
	file_api_proxy_service_proxy_proto_goTypes = nil
	file_api_proxy_service_proxy_proto_depIdxs = nil
}
